version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: taskmanager_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: taskmanager
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - taskmanager_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/taskmanager --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Node.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager_app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/taskmanager?authSource=admin
      JWT_ACCESS_SECRET: dev_jwt_access_secret_change_in_production_min_32_chars
      JWT_ACCESS_EXPIRY: 15m
      JWT_REFRESH_SECRET: dev_jwt_refresh_secret_change_in_production_min_32_chars
      JWT_REFRESH_EXPIRY: 7d
      CORS_ORIGIN: http://localhost:3001
      LOG_LEVEL: debug
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - uploads:/usr/src/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - taskmanager_network
    command: npm run dev

  # Mongo Express (MongoDB Admin UI)
  mongo-express:
    image: mongo-express:1.0-20
    container_name: taskmanager_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - taskmanager_network

networks:
  taskmanager_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  uploads:
    driver: local
